version: "3.2"
services:
  redis:
    restart: always
    image: redis:5.0.13-alpine
    command: redis-server
    ports:
      - "6379:6379"
    user: root

  db:
    restart: always
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - "5432:5432"

  api:
    image: sergienkoandrew/djangomessenger-api
    restart: always
    container_name: code
    command: bash -c "python wait_for_db.py &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    image: sergienkoandrew/djangomessenger-api
    command: bash -c "pip install gevent &&
                      celery -A app worker -l info -P gevent"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - api
    user: root

  frontend:
    image: sergienkoandrew/djangomessenger-front:1
    restart: always
    command: npm start
    container_name: front
    ports:
      - "80:3000"
    stdin_open: true
    depends_on:
      - api
volumes:
  pgdata: