version: "3.2"
services:
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass 5j426FnDKe
    ports:
      - "6379:6379"

  api:
    image: sergienkoandrew/djangomessenger-api
    restart: always
    container_name: code
    command: bash -c "python wait_for_db.py &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    image: sergienkoandrew/djangomessenger-api
    command: bash -c "celery -A app worker -l info -P gevent"
    env_file:
      - ./.env.dev
    depends_on:
      - api
    user: root

  frontend:
    image: sergienkoandrew/djangomessenger-front
    restart: always
    command: npm start
    container_name: front
    ports:
      - "80:3000"
    stdin_open: true
    depends_on:
      - api
volumes:
  pgdata: