version: "3.2"
services:
  redis:
    restart: always
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"

  db:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postresql/data
    env_file:
      - .env.dev
    ports:
      - "5432:5432"

  api:
    image: sergienkoandrew/djangomessenger:api3
    restart: always
    container_name: code
    command: bash -c "python wait_for_db.py &&
                      python manage.py migrate &&
                      python manage.py runserver"
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    image: sergienkoandrew/djangomessenger:api3
    command: bash -c "pip install gevent &&
                      celery -A app worker -l info -P gevent"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - api

  frontend:
    image: sergienkoandrew/djangomessenger:front2
    restart: always
    command: npm start
    container_name: front
    ports:
      - "80:3000"
    stdin_open: true
    depends_on:
      - api
volumes:
  pgdata: