# Generated by Django 4.0.3 on 2022-06-05 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('personal', 'personal'), ('group', 'group')], default='personal', max_length=8),
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.ManyToManyField(default=False, related_name='reads', to=settings.AUTH_USER_MODEL),
        ),
    ]
