# Generated by Django 4.0.3 on 2022-05-26 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_channeluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_message', to='chat.message'),
        ),
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('personal', 'personal'), ('group', 'group')], default='personal', max_length=8),
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.ManyToManyField(default=False, related_name='reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChannelUser',
        ),
    ]
