# Generated by Django 4.0.3 on 2022-05-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_channeluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('personal', 'Personal'), ('group', 'Group')], default='Personal', max_length=8),
        ),
    ]
