# Generated by Django 4.0.3 on 2022-05-26 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_alter_chat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.ManyToManyField(default=False, related_name='reads', to=settings.AUTH_USER_MODEL),
        ),
    ]
