# Generated by Django 4.0.3 on 2022-06-23 11:33

import app.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_message_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=app.storage_backends.PublicMediaStorage(), upload_to='')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=10)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat.message')),
            ],
        ),
    ]
