# Generated by Django 4.0.3 on 2022-06-28 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    operations = [
        migrations.AlterField(
            model_name='file',
            name='message',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat.message'),
        ),
    ]
