# Generated by Django 4.0.3 on 2022-06-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_read'),
        ('files', '0002_alter_file_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat.message'),
        ),
    ]
